#!/usr/bin/python
from distutils.core import setup, Extension
import sys

__version__ = "1.0.0"

if sys.platform == "darwin":
    extra_flags=['-arch', 'i386', '-arch', 'x86_64']
else:
    extra_flags=[]

setup(
    name         = "cx509",
    version      = __version__,
    author       = "Dave Baggett",
    author_email = "dmb@arcode.com",
    url          = "http://www.arcode.com/",
    description  = "X.509 certificate, parsed using parser generated by asn1c.",
    license      = "N/A",
    platforms    = ["Platform Independent"],
    ext_modules  = [Extension(
            name='cx509', 
            sources=['cx509.c'],
            extra_compile_args=extra_flags,
            extra_link_args=extra_flags
            )],
)
