#!/usr/bin/python
from distutils.core import setup, Extension
import sys
from glob import glob

__version__ = "1.0.0"

if sys.platform == "darwin":
    extra_flags=['-arch', 'i386', '-arch', 'x86_64']
else:
    extra_flags=[]

# Add prebuilt X.509 C sources to sources list
sources = glob("asn1c/examples/sample.source.PKIX1/*.c")
sources.extend(glob("asn1c/examples/sample.source.PKCS1/*.c"))
extra_flags.extend([
    '-Iasn1c/examples/sample.source.PKIX1',
    '-Iasn1c/examples/sample.source.PKCS1',
    '-DPDU=Certificate'
])
sources.append('cx509.c')
sources.remove('asn1c/examples/sample.source.PKIX1/converter-sample.c')

setup(
    name         = "cx509",
    version      = __version__,
    author       = "Dave Baggett",
    author_email = "dmb@arcode.com",
    url          = "http://www.arcode.com/",
    description  = "X.509 certificate, parsed using parser generated by asn1c.",
    license      = "N/A",
    platforms    = ["Platform Independent"],
    ext_modules  = [Extension(
            name='cx509', 
            sources=sources,
            extra_compile_args=extra_flags,
            extra_link_args=extra_flags
            )],
)
